Extend SET_ATTITUDE_TARGET message for 3D thrust setpoints
mavlink/mavlink pull request #1600
Opened 2021-02-28 20:23 UTC by Jaeyoung-Lim

**Problem Description**
With recent development of fully actuated systems and more complex actuation being available on VTOL vehicles, we need a way to conveniently set 3D thrust setpoints on vehicles. 

This adds a 3D thrust setpoint in the SET_ATTITUDE_TARGET to support fully actuated vehicles

The reference implementation is provided in https://github.com/PX4/PX4-Autopilot/pull/16994

2021-02-28 23:08 UTC, amilcarlucas requested changes
What are the units?

2021-03-01 05:56 UTC, Jaeyoung-Lim commented
@amilcarlucas It is normalized thrust therefore it is unitless. Same as the thrust

2021-03-01 09:30 UTC, amilcarlucas commented
Then add it to the description of this message as well.

2021-03-01 10:43 UTC, Jaeyoung-Lim commented
@amilcarlucas Done

2021-03-02 07:28 UTC, Jaeyoung-Lim commented
@amilcarlucas Is there anything else that needs to be improved?

2021-03-02 10:36 UTC, amilcarlucas commented
Now you need for it to get reviewed by the Team.
I do not like that it changes a stable message. I think that only wip messages should be changed.

2021-03-02 11:06 UTC, Jaeyoung-Lim commented
@amilcarlucas This has been something that is limiting the development for a while, and since it is a stable message I also understand that messages shouldn't be changed. Therefore I added it as an extension.

If there is nothing to be changed from your side, would you be able to re-review this PR?

2021-03-02 11:38 UTC, amilcarlucas commented
Can you provide an ardupilot reference implementation as well?

2021-03-02 11:48 UTC, Jaeyoung-Lim commented
@amilcarlucas Unfortunately not. I am not familiar with Ardupilot. As far as I understand it is not required to provide a reference implementation for multiple autopilots.

May I ask why this is needed for re-reviewing this PR?

2021-03-02 12:40 UTC, amilcarlucas commented
No second reference implementation is required but it woul not hurt.

2021-03-02 12:41 UTC, amilcarlucas approved these changes

2021-03-02 12:57 UTC, Jaeyoung-Lim commented
@amilcarlucas Thanks!

2021-03-10 07:13 UTC, Jaeyoung-Lim commented on message_definitions/v1.0/common.xml
> +        <description>Use 3D body thrust setpoint instead of throttle</description>
@hamishwillee This is following the foot step of the `POSITION_TARGET_TYPEMASK`: https://github.com/mavlink/mavlink/blob/35b3f5e51eeb807486a1b079565e74d4e6ad3418/message_definitions/v1.0/common.xml#L3523. The problem with defining it as a ignore is that if none of the ignore flags it means that the user wants to use both as a default, which is not a valid case

2021-03-11 02:36 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +        <description>Use 3D body thrust setpoint instead of throttle</description>
OK!

2021-03-23 03:00 UTC, jbwillis commented
I am interested in using this with ROS1 for testing a VTOL control algorithm I've been working on. @Jaeyoung-Lim has there been effort in updating MAVROS to support it?

2021-03-23 05:19 UTC, Jaeyoung-Lim commented
@jbwillis mavros is only mapping ros topics to mavlink, which requires this PR to be merged. Therefore the answer is no.
In case for your use case, the real part missing is the mavlink integration into the firmware for VTOLS

2021-03-23 21:29 UTC, jbwillis commented
@Jaeyoung-Lim Right, just wondering if there was some parallel development going on with MAVROS as well. I'm planning on working off of your branches on the PX4 autopilot.

2021-03-23 21:42 UTC, Jaeyoung-Lim commented
@jbwillis Great! I will push this up to mavros once this is merged

2021-03-24 22:34 UTC, hamishwillee commented
This is a non-breaking/compatible extension which appears to make sense. I will contact @auturgy again for comment.

2021-03-24 22:43 UTC, auturgy commented
Looks fine. Happy to merge

2021-03-24 23:05 UTC, LorenzMeier approved these changes

2021-03-24 23:05 UTC, merged