common: fix HDOP/VDOP unit scaling
mavlink/mavlink pull request #1603
Opened 2021-03-04 12:13 UTC by julianoes

I believe that the HDOP/VDOP values are generally scaled by 100 and we should therefore document it that way.

PX4:
*.01f when the UBX values are read:
https://github.com/PX4/PX4-GPSDrivers/blob/c278eb48e1b57e6b789242324e28581caf9ccf96/src/ubx.cpp#L1815-L1816

*100 before the values are sent out:
https://github.com/PX4/PX4-Autopilot/blob/5bbc66f3afe99e75852e9b3660a5de4d2fc0b902/src/modules/mavlink/mavlink_messages.cpp#L1393-L1394

ArduPilot:
It seems to be *100 everywhere without conversion from UBX:
https://github.com/ArduPilot/ardupilot/blob/ecf928d68ba497dd2502ab56037f6aaa1bc298e2/libraries/AP_GPS/AP_GPS_UBLOX.cpp#L1280-L1281
And sent out as is:
https://github.com/ArduPilot/ardupilot/blob/ecf928d68ba497dd2502ab56037f6aaa1bc298e2/libraries/AP_GPS/AP_GPS.cpp#L1238-L1239

2021-03-04 14:02 UTC, amilcarlucas requested changes

2021-03-04 14:02 UTC, amilcarlucas commented on message_definitions/v1.0/common.xml
> +      <field type="uint16_t" name="epv">GPS VDOP vertical dilution of position (unitless * 100). If unknown, set to: UINT16_MAX</field>
```suggestion
      <field type="uint16_t" name="eph">GPS HDOP horizontal dilution of position (unitless*100). If unknown, set to: UINT16_MAX</field>
      <field type="uint16_t" name="epv">GPS VDOP vertical dilution of position (unitless*100). If unknown, set to: UINT16_MAX</field>
```

2021-03-04 14:02 UTC, amilcarlucas commented on message_definitions/v1.0/common.xml
> +      <field type="uint16_t" name="epv">GPS VDOP vertical dilution of position (unitless * 100). If unknown, set to: UINT16_MAX</field>
for consistency

2021-03-04 14:17 UTC, julianoes commented on message_definitions/v1.0/common.xml
> +      <field type="uint16_t" name="epv">GPS VDOP vertical dilution of position (unitless * 100). If unknown, set to: UINT16_MAX</field>
Oops, thanks!

2021-03-09 17:44 UTC, amilcarlucas commented
looks good to me, but I would like to ear @WickedShell's input on this

2021-03-09 17:54 UTC, WickedShell commented
That is what ArduPilot's doing, so from an ArduPilot point of view seems reasonable.

2021-03-09 18:13 UTC, julianoes commented
Thanks @amilcarlucas and @WickedShell!

2021-03-09 18:13 UTC, merged

2021-03-15 08:24 UTC, amilcarlucas commented
Why is this still marked as open? A couple of lines above it says the commit has been merged.