Add MAV_CMD_DELETE_IMAGE command
mavlink/mavlink pull request #1647
Opened 2021-06-08 11:57 UTC by MatejFranceskin

Add a command for deleting image from the image log.

Related messages and commands:

CAMERA_IMAGE_CAPTURED contains index in image log
CAMERA_CAPTURE_STATUS  contains total number of images in the image log
MAV_CMD_STORAGE_FORMAT has an option to reset image log
MAV_CMD_REQUEST_CAMERA_IMAGE_CAPTURE to request CAMERA_IMAGE_CAPTURED from image log

2021-06-09 00:07 UTC, hamishwillee commented
So the use case is that you have some UI for deleting images and you want to keep the other camera data consistent? Rather than just deleting it through some other UI? Sounds sensible to me. @dogmaphobic @julianoes any comments?

If this goes though, could you provide associated update in https://mavlink.io/en/services/camera.html#still-image-capture docs?

2021-06-09 05:44 UTC, MatejFranceskin commented
Yes, this is the use case. When deleting images we want to keep the other data consistent.
I will update the docs too.

2021-06-09 06:39 UTC, julianoes commented on message_definitions/v1.0/common.xml
> +        <description>Delete image from image log. This operation will decrement all image indexes after deleted image and number of images in CAMERA_CAPTURE_STATUS.image_count.</description>
So for a camera implementation you would then rename all images to match the new indices? This doesn't sound intuitive to me. Usually, with cameras, when I delete a camera it would leave everything else untouched.

2021-06-09 09:31 UTC, julianoes commented on message_definitions/v1.0/common.xml
> +        <description>Delete image from image log. This operation will decrement all image indexes after deleted image and number of images in CAMERA_CAPTURE_STATUS.image_count.</description>
I guess I connected the two in my mind, I guess my assumption was not right then.

However, @hamishwillee raised a very good point:
If you subscribe to the CAMERA_IMAGE_CAPTURED on multiple MAVLink devices, then you don't know that a picture has been deleted and you will be off when requesting one. So basically, if you move the indices of all following images, it creates a synchronization problem.

To me it would be easier to leave the index as is and avoid these problems. I don't see what the advantage would be of moving them all.

2021-06-09 09:51 UTC, MatejFranceskin commented on message_definitions/v1.0/common.xml
> +        <description>Delete image from image log. This operation will decrement all image indexes after deleted image and number of images in CAMERA_CAPTURE_STATUS.image_count.</description>
What if we add a hash or crc of the whole photo log so that we could detect that it has to be resynced?

2021-06-09 10:05 UTC, MatejFranceskin commented on message_definitions/v1.0/common.xml
> +        <description>Delete image from image log. This operation will decrement all image indexes after deleted image and number of images in CAMERA_CAPTURE_STATUS.image_count.</description>
The implementation should rely on photo names (URLs) and not indexes. So that it one index is deleted and others shift it doesn't create a problem. However I don't know how to specify this correctly in the protocol definition.

2021-06-09 15:05 UTC, MatejFranceskin commented on message_definitions/v1.0/common.xml
> +        <description>Delete image from image log. This operation will decrement all image indexes after deleted image and number of images in CAMERA_CAPTURE_STATUS.image_count.</description>
I made a change so that I removed the part where indexes should be shifted after deleting image log entry. It would be better to keep the index "empty" so that if that entry is queries it would return DENIED or  CAMERA_IMAGE_CAPTURED with empty file_url.

2021-06-10 01:06 UTC, hamishwillee commented
@MatejFranceskin @julianoes That change makes me more comfortable - and less work for all concerned.

Question, the wording is "Delete image from image log." and "number for image log entry to be deleted". 
I read that as. 
1. I have a folder full of images
2. I have a log of those images
3. I call this message to delete the record of the image. The index is now empty.
4. The image itself might still be present in that folder.

Can you confirm this interpretation. I.e. this is an instruction that actions on the log - there is no assumption that anything has happened to the underlying image.

2021-06-10 06:24 UTC, julianoes approved these changes

2021-06-10 09:45 UTC, MatejFranceskin commented
@hamishwillee Yes, this is an instruction for the log of images. The image can remain on the storage, but if it is not in the log then GCS will not be able to get its URL.

2021-06-16 00:36 UTC, hamishwillee commented
@MatejFranceskin @julianoes I have renamed and edited this to make it clear that it is a removal from log and not a deletion of file. I think that is necessary because
- this wasn't absolutely clear to me
- it is quite possible and reasonable you might also want to have an API to actually delete images from media - that can now exist in parallel

Are you OK with the new message name and text? If so I think we are good to merge.

2021-06-16 12:57 UTC, julianoes requested changes

2021-06-16 12:57 UTC, julianoes commented on message_definitions/v1.0/common.xml
> +        <param index="1" label="Number" minValue="0" increment="1">Sequence number for image log entry to be removed.</param>
I don't understand why you would want that. Deleting a picture file makes sense. Deleting a line from a log, that's not intuitive to me.

2021-06-17 01:12 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +        <param index="1" label="Number" minValue="0" increment="1">Sequence number for image log entry to be removed.</param>
@MatejFranceskin This question is for you.

2021-06-18 09:43 UTC, MatejFranceskin commented on message_definitions/v1.0/common.xml
> +        <param index="1" label="Number" minValue="0" increment="1">Sequence number for image log entry to be removed.</param>
But what would happen if you remove the image and keep it referenced in a log? How can GCS know that image was removed? We don't want to try to download the images all the time just to get negative ACK to figure out that it was deleted. We would like to figure it out only from the image log.
Let's go back to what I need: I need a command that would remove the image file on the vehicle and from the log. The log count wouldn't be decremented, just the deleted image URL in the log would be set to empty.

2021-06-18 11:42 UTC, MatejFranceskin commented on message_definitions/v1.0/common.xml
> +        <param index="1" label="Number" minValue="0" increment="1">Sequence number for image log entry to be removed.</param>
Actually what I need is delete image and this can be done via HTTP server that is used to download actual images. In this case what happens to get image log after that is left to implementation. Requesting log entry for deleted image can return "denied" or empty URL.
In this case we can close this PR.

2021-06-21 14:24 UTC, julianoes commented on message_definitions/v1.0/common.xml
> +        <param index="1" label="Number" minValue="0" increment="1">Sequence number for image log entry to be removed.</param>
I think I agree, yes.

2021-06-21 15:16 UTC, closed without merging