SYS_STATUS: Use flag 0x80000000 for parachute status
mavlink/mavlink pull request #1751
Opened 2021-11-24 08:03 UTC by ThomasDebrunner

2021-11-26 11:33 UTC, julianoes commented
@hamishwillee @auturgy this change is interesting because it can't be prototyped in another dialect first. And it's tricky as it's the very last bit :smile:

2021-11-27 08:14 UTC, auturgy commented on message_definitions/v1.0/common.xml
> +      <entry value="2147483648" name="MAV_SYS_STATUS_PARACHUTE">
Suggest:
<entry value="2147483648" name="MAV_SYS_STATUS_RECOVERY_SYSTEM">
<description>0x80000000 Recovery system (parachute, balloon, retracts etc)</description>

2021-11-27 08:15 UTC, auturgy commented on message_definitions/v1.0/common.xml
> +      <entry value="2147483648" name="MAV_SYS_STATUS_PARACHUTE">
Excuse dodgy markup: unfortunately github parses it in comments so I had to remove a couple of tags

2021-11-27 08:18 UTC, auturgy requested changes
I think it's as good a use as any for the last bit: it does force us to think about what we do next though.  See suggestion to generalise from parachute to recovery system.

2021-11-27 21:55 UTC, peterbarker commented
What are the suggested semantics of the relevant fields, present/enabled/healthy?

2021-11-30 08:01 UTC, ThomasDebrunner commented on message_definitions/v1.0/common.xml
> +      <entry value="2147483648" name="MAV_SYS_STATUS_PARACHUTE">
Agree, that's a good option

2021-11-30 08:09 UTC, ThomasDebrunner commented on message_definitions/v1.0/common.xml
> +      <entry value="2147483648" name="MAV_SYS_STATUS_PARACHUTE">
Changed the PR

2021-11-30 08:13 UTC, ThomasDebrunner commented
> What are the suggested semantics of the relevant fields, present/enabled/healthy?

Present: System is fitted to the vehicle and detected
Enabled: System is set to trigger in an emergency
Healthy: There are no issues detected with the system

Is that what you mean?

2021-12-01 02:22 UTC, hamishwillee reviewed
>> And it's tricky as it's the very last bit 😄

> I think it's as good a use as any for the last bit: it does force us to think about what we do next though. See suggestion to generalise from parachute to recovery system.

@auturgy I think it's best for us to think about what we do next before we merge this.

Specifically, if we decided that we would extend [SYS_STATUS](https://mavlink.io/en/messages/common.html#SYS_STATUS) with a second triplet of fields then we would want to use this last flag to indicate that the following flag set is in use, and the first flag of the new set for the recovery system.

I'm not advocating, but I do think it is worth asking the question before we remove the choice. What are the options?

(otherwise yes, this looks like a good use of the last flag).

2021-12-03 09:59 UTC, ThomasDebrunner commented
@hamishwillee I like the idea of adding another triplet for status bits and using the last bit to indicate the presence of the second triplet. 
I pushed another commit for that. They can be squashed on merge

2021-12-03 10:10 UTC, julianoes reviewed
I think this looks correct.

2021-12-06 23:07 UTC, tridge commented
no objections from me, seems like the best option

2021-12-07 23:04 UTC, hamishwillee reviewed
@ThomasDebrunner Thanks very much. Looks like we have broad consensus on this. Can you run format on the file (it fails the test). On ubuntu you can do this from the mavlink repo folder using the command:
```
./scripts/format_xml.sh ./message_definitions/v1.0/common.xml
```

2021-12-07 23:07 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <entry value="2147483648" name="MAV_SYS_STATUS_EXTENSION_USED">
To avoid any ambiguity on which field(s) should this be set? I.e. do we require it set on all the `onboard_control_sensors_xxx` fields, or just (say) `onboard_control_sensors_present` (I propose just onboard_control_sensors_present)

2021-12-08 06:27 UTC, julianoes commented on message_definitions/v1.0/common.xml
> +      <entry value="2147483648" name="MAV_SYS_STATUS_EXTENSION_USED">
Good point. `onboard_control_sensors_present` sounds sensible.

2021-12-08 09:37 UTC, merged