MAV_WINCH_STATUS_CLUTCH_ENGAGED: clarify definition
mavlink/mavlink pull request #1781
Opened 2022-01-12 06:21 UTC by hamishwillee

DO NOT MERGE UNLESS AGREED WITH @rmackay9 

`MAV_WINCH_STATUS_CLUTCH_ENGAGED` text was "Winch clutch is engaged allowing motor to move freely". Those things are mutually exclusive - an engaged clutch is driving the motor. 

As discussed in https://github.com/mavlink/mavlink/pull/1766#discussion_r779898408 we can't change the meaning because it is being used currently. But we can clarify what it really means and that we understand it is misnamed. 

@rmackay9 Does this work for you if I merge it now. The idea is that there is now no longer any pressure on you to change `MAV_WINCH_STATUS_CLUTCH_ENGAGED` in any kind of timely manner, or really at all if it is not possible to do safely.

2022-01-30 22:12 UTC, hamishwillee commented
@rmackay9 Can I merge this please?

2022-02-23 03:11 UTC, hamishwillee commented
@rmackay9 Ping.

2026-06-25 05:53 UTC, hamishwillee commented
@rmackay9 Can you confirm if you want this. If not anyone else implementing this will assume it does what it says on the box. IN which case ArduPilot will be non-compliant. 

If no response I'll close this next time I'm reviewing - could be days or months.

2026-09-02 05:23 UTC, peterbarker commented on message_definitions/v1.0/common.xml
> +          Note that this flag is incorrectly named ("clutch engaged" should mean that the motor is driving the winch).</description>
```suggestion
        <description>Winch clutch is engaged. Contrary to popular usage, "engaged" does not indicate the spool is engaged with the motor; "engaged" here indicates the (sprung) clutch is actively being operated i.e. disengaging the motor from the spool.</description>
```

I strongly suggest we consider renaming this enumeration entry - bizarrely to exactly the opposite meaning:

`MAV_WINCH_STATUS_CLUTCH_DISENGAGED`

2026-09-02 05:29 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
>        <entry value="8" name="MAV_WINCH_STATUS_CLUTCH_ENGAGED">
```suggestion
      <entry value="8" name="MAV_WINCH_STATUS_CLUTCH_DISENGAGED">
```

2026-09-02 05:31 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +          Note that this flag is incorrectly named ("clutch engaged" should mean that the motor is driving the winch).</description>
Yes, just accepted a change like that. Its not going to break anyone at runtime, and will be a very good hint if anyone is currently using it.

2026-09-02 05:43 UTC, peterbarker requested changes

2026-09-02 05:43 UTC, peterbarker commented on message_definitions/v1.0/common.xml
> +          Note that this flag is incorrectly named ("clutch engaged" should mean that the motor is driving the winch).</description>
```suggestion
          .</description>
```

2026-09-02 06:06 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +          .</description>
```suggestion
        <description>Winch clutch is disengaged. The motor is moving freely and not driving the winch.</description>
```

2026-09-02 09:01 UTC, peterbarker commented
@hamishwillee Randy wasn't able to add the meeting this week, so I've tagged this for call next week.

2026-09-02 22:16 UTC, rmackay9 approved these changes
Sorry for holding things up.  It just means that on the AP side we need to fix the AP_WInch library which I've created an issue for https://github.com/ArduPilot/ardupilot/issues/34273

2026-09-03 02:13 UTC, peterbarker approved these changes

2026-09-03 02:20 UTC, merged

2026-09-03 03:40 UTC, hamishwillee commented
Thanks so much @peterbarker ! Happy days.