MAV_CMD_RUN_PREARM_CHECKS - capture intent better
mavlink/mavlink pull request #1857
Opened 2022-06-15 04:26 UTC by hamishwillee

This attempts to better capture a comment from @MaEtUgR in https://github.com/mavlink/mavlink/pull/1651#issuecomment-1150885749 that he wasn't entirely clear that MAV_CMD_RUN_PREARM_CHECKS  was needed for the case where prearm checks are run at fairly low rate, or not run when things happen that might cause the armable state to change.

What I've done is added that information. I also noted that SYS_STATUS is one way the results might be reported. MAVLink doesn't actually specify anything about this, but PX4 will doubtless use EVENTS in future (and I suspect ArduPilot may too).

@MaEtUgR @peterbarker is this acceptable?

2022-06-16 07:30 UTC, peterbarker requested changes
I've no problem with this if people feel it is clearer.

2022-06-16 07:30 UTC, peterbarker commented on message_definitions/v1.0/common.xml
> +          This command should should return MAV_RESULT_ACCEPTED if it is able to run the checks.
```suggestion
          This command should should return MAV_RESULT_ACCEPTED if it will run the checks.
```

2022-06-16 23:40 UTC, hamishwillee commented
Thanks @peterbarker . @MaEtUgR does this address your concern.

2022-06-30 00:45 UTC, hamishwillee commented
Thanks all. Merging as I think this is certainly no worse than before, and hopefully addresses concerns raised.

2022-06-30 00:45 UTC, merged

2022-07-06 09:22 UTC, MaEtUgR reviewed
Thanks @hamishwillee !
Sorry I'm again late. This already helps a lot but I added some suggestions. Are they useful? Should I make a pr?

2022-07-14 01:43 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +          This command should should return MAV_RESULT_ACCEPTED if it will run the checks.
Thanks. Fixed in https://github.com/mavlink/mavlink/commit/8d100f98609a258b406ffee3b58c683346e04975

2022-07-14 01:44 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +          This allows preflight checks to be run on demand, which may be useful on systems that normally run them at low rate, or which do not trigger checks when the armable state might have changed
I think we can leave this. The point is that they are run on demand, which can be useful if they are not run regularly enough to always be up to date.