common: extend MISSION_CURRENT
mavlink/mavlink pull request #1869
Opened 2022-08-03 07:48 UTC by julianoes

The message MISSION_CURRENT is a bit limited as it sends the current mission item sequence but no context.

My proposition would be to include the total as well as the status of an ongoing mission.

Related to https://github.com/mavlink/mavlink/pull/1868.

2022-08-03 08:06 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <entry value="0" name="MISSION_STATUS_NOT_STARTED">
I think you need to start from `MISSION_STATUS_UNKNOWN`=0 to indicate systems that don't support mission status.

2022-08-03 08:07 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +        <description>The mission has not been started yet. This is the case after upload.</description>
Probably technically "This is the case after upload when there is no active mission". I mean if you upload a mission when there is an active mission you will be in the running state.

2022-08-03 20:47 UTC, julianoes commented on message_definitions/v1.0/common.xml
> +      <entry value="0" name="MISSION_STATUS_NOT_STARTED">
Good point!

2022-08-03 20:47 UTC, julianoes commented on message_definitions/v1.0/common.xml
> +        <description>The mission has not been started yet. This is the case after upload.</description>
Right.

2022-08-04 00:40 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="uint8_t" name="status" enum="MISSION_STATUS">Total number of mission items</field>
```suggestion
      <field type="uint8_t" name="status" enum="MISSION_STATUS">Mission state.</field>
```

2022-08-04 00:42 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +        <description>The mission has been paused with autocontinue=false.</description>
Do we need `with autocontinue=false` clarification at the end here?

To put is another way, if I manually hold would this be the state that is set? If the mission auto pauses is this what I would set.

2022-08-04 03:06 UTC, julianoes commented on message_definitions/v1.0/common.xml
> +        <description>The mission has been paused with autocontinue=false.</description>
I need to create a second "Paused" for that, I think.

2022-08-04 03:07 UTC, julianoes commented on message_definitions/v1.0/common.xml
> +      <field type="uint8_t" name="status" enum="MISSION_STATUS">Total number of mission items</field>
Thanks, I'll fix that.

2022-08-04 05:02 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      </entry>
This is accurate for PX4 but leaks "implementation details" and also means there's a state (paused in mission by user) that isn't captured for ArduPilot. I think we can do this without the implementation details, and also capture that you might have changed flight mode - since changing a flight mode will pause an active mission. How about:

```suggestion
      <entry value="3" name="MISSION_STATUS_PAUSED_MANUAL">
        <description>The mission has been paused by the a user command or by changing the flight mode.</description>
      </entry>
      <entry value="4" name="MISSION_STATUS_PAUSED_AUTO">
        <description>The mission has been automatically paused due to completion of an item with autocontinue=false.</description>
      </entry>
```

2022-08-09 23:55 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
>        <description>Message that announces the sequence number of the current active mission item. The MAV will fly towards this mission item.</description>
1. It's worth saying this is streamed. 
   - Should this be streamed when the mission is paused/completed or only when the mission is active and running? 
choose to stream in this mode but not when in a normal loiter.
     - My thinking is that this should only be streamed if there a mission uploaded, but otherwise it can be streamed all the time.
   - Is there a rate at which this is streamed?
2. It is worth saying this is emitted after setting mission_current

Is this OK?

```suggestion
      <description>Message that announces the sequence number of the current target mission item (that the system will fly towards/execute when the mission is running). This should be streamed and emitted following MAV_CMD_DO_SET_MISSION_CURRENT or SET_MISSION_CURRENT.</description>
```

2022-08-10 00:31 UTC, hamishwillee commented
@peterbarker Would appreciate your comment on this.

At the moment you can infer some of the states of the mission from the mode (particularly in ArduPilot where pause is a sub mode of auto). This is not so easy in PX4 where "pause = hold mode" (except after an "autocontinue" pause). I don't think it is easy in either case to know if a mission has actually completed.

So this adds state information to the MISSION_CURRENT, along with the total number of mission items, so a user doesn't need to separately query the mission for that.

2022-08-10 00:44 UTC, julianoes commented on message_definitions/v1.0/common.xml
>        <description>Message that announces the sequence number of the current active mission item. The MAV will fly towards this mission item.</description>
> Should this be streamed when the mission is paused/completed or only when the mission is active and running?

It should always be streamed, so that you know what the next waypoint is even before you switch to mission mode.

The rate should be something like 1 Hz but that's always configurable. And as an answer to SET_MISSION_CURRENT as you suggest.

2022-08-10 01:19 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
>        <description>Message that announces the sequence number of the current active mission item. The MAV will fly towards this mission item.</description>
Thanks @julianoes . I updated the suggestion above. 

But w.r.t. "always streaming" what if there is no mission uploaded? How about in this case a new status and values for the current and total set to 0 ?

2022-08-10 01:20 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
>        <description>Message that announces the sequence number of the current active mission item. The MAV will fly towards this mission item.</description>
And note that this might have to change a bit depending on what ArduPilot do.

2022-08-10 05:29 UTC, julianoes commented on message_definitions/v1.0/common.xml
>        <description>Message that announces the sequence number of the current active mission item. The MAV will fly towards this mission item.</description>
I think sending it with 0 would be ok yes.

2022-08-10 08:13 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="uint16_t" name="total">Total number of mission items</field>
```suggestion
      <field type="uint16_t" name="total">Total number of mission items. 0 if there is no mission.</field>
```

2022-08-10 08:15 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +    </enum>
```suggestion
      </entry>
      <entry value="6" name="MISSION_STATUS_NO_MISSION_UPLOADED">
        <description>The Mission has been finished.</description>
      </entry>
    </enum>
```

2022-08-10 09:21 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      </entry>
@julianoes Refining these a bit. The cases are "paused out of auto" and "paused in auto".

```suggestion
      <entry value="3" name="MISSION_STATUS_PAUSED_MODE_CHANGE">
        <description>The mission has been paused by changing the flight mode.</description>
      </entry>
      <entry value="4" name="MISSION_STATUS_PAUSED_AUTO">
        <description>The mission has been paused in mission mode. For example, automatically paused due to completion of an item with autocontinue=false.</description>
      </entry>
```

2022-08-11 00:00 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +        <description>The Mission has been finished.</description>
```suggestion
        <description>There is no mission on the vehicle.</description>
```

2022-08-11 12:45 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +    <enum name="MISSION_STATUS">
We might need more work on these states in light of what ArduPlane does. For example when it is complete, it goes straight into RTL. So at this point the mission is complete but the mode is something else.

2022-08-12 00:37 UTC, hamishwillee commented
Mission states are a little complex and we may need to rethink this to make sure that we're sending the right information. What that information depends on who/how this is consumed. In summary though

Summary, IMO
- States reflect mission engine when it is running: unknown, no-mission, not-started, active, paused, finished.
- If you're in another mode the mission engine is "suspended" - this is a useful distinction or you need to have multiple states to also cover the suspended case. You might infer this from the current mode, but I think we should expose this as a field to avoid the system having to know anything about autopilot modes. It is effectively "not mission mode or submode".

This is a change from having an option  "Paused not in auto". There is a difference between saying "Pausing a mission mission moves it into hold mode" and "PX4 implements pause as hold". I THINK we are the former - certainly the mode is advertised as Hold in QGC.

Make sense? There is some useful info about what the systems do below.

----

TLDR;

The "reality" is that we have a mission state machine that might have states "like[+]":
- mission not uploaded
- mission not yet started - mission uploaded and all jump counters[++] reset. But has not yet been started.
- mission running - mission is executing mission items
- mission paused - mission is pausing within the context of the mission mode - ie in a submode.
- mission complete - stopped

[+]: I say "like" because some implementations use the same "state" _mission stopped_ for mission _not yet started_ and _complete_. Further, plane does not support paused, even in theory.
[++] Jump counters are separate from state.

Then on top of this we have the case where a mission may be _suspended_ - i.e. you're in another mode like "Hold". In this case. The mission is not running at all but the state still exists and might be re-entered.

ArduCopter matches those states _precisely_ (as sub modes).
- so if you are paused you're still in mission mode. If moving you'll move to a graceful stop.
- If you leave the mission to another mode it is suspended. Say you move to hold, you'd immediately hold rather than gracefully stop.
- FYI you can't start mission from the initial state by calling the set mission current
- ArduPilot does not implement autocontinue flag.

ArduPlane does not implement the  mission paused state; you cannot pause mission, you can only suspend it by changing mode.
- The pause/continue command is not implemented because it doesn't make sense with this paradigm. Though continue might, if we assumed that this also requires a switch-to-mode.
- If you run out of items in the mission (complete) the internal state changes to mission-stop and the mode is forced to RTL. Sending message to set the current mission item sets the state back to active - you then have to change the mode back to resume.
- The plane never wants to say it is paused.
- The plane state is almost completely inferrable - you're either in mission mode and executing or stopped or you are in some other mode. 
- FYI you CAN start mission from the initial state by calling the set mission current

PX4 does a mix of these two, implementing both pause sub modes and emulating pause-as-switch to mode:
- It has mission sub mode for the pause state when `autocontinue=false`
- It has mission sub mode for the complete state (right?).
- Pausing a mission is implemented as moving to hold mode. But this is not done using a pause, but using a do_reposition.
- Restarting a mission is implemented as moving back to mission mode.
- Not sure/ do we know how PX4 sees an explicit mode change vs pause when running a mission? i.e. does it think of itself as in hold mode, or does it somehow know that actually it is in a paused mission mode?

So:
- Arduplane might want to output states: unknown, no-mission, not-started, active, complete (internally, both "not started" and "complete" are "stopped").
- ArduCopter and PX4 might want to output states: unknown, no-mission, not-started, active, paused, finished.

2022-08-15 23:54 UTC, tridge requested changes

2022-08-15 23:54 UTC, tridge commented on message_definitions/v1.0/common.xml
> +      <field type="uint16_t" name="total">Total number of mission items. 0 if no mission is present on the vehicle.</field>
zero can't be used as would break with implementations that don't have this extension, we need zero to mean unknown

2022-08-17 03:04 UTC, julianoes commented on message_definitions/v1.0/common.xml
> +      <field type="uint16_t" name="total">Total number of mission items. 0 if no mission is present on the vehicle.</field>
That's true. So we need to set it to UINT16_MAX for "no mission"/"empty mission", 0 for unknown, and > 0 else for a valid mission.

2022-08-17 04:53 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +    </enum>
Change MISSION_STATUS to reflect the "ideal" states of the mission finite state machine, as identified in https://github.com/mavlink/mavlink/pull/1869#issuecomment-1212621078. 

Because this is actually the state machine and not the mission, I have renamed to MISSION_FSM_STATE. That way people are less likely to think "but I paused my mission by moving to Hold mode, so I should emit paused". 

I will add a value for "suspended".


```suggestion
    <enum name="MISSION_FSM_STATE">
      <description>
        States of the mission finite state machine.
        Note that these states are independent of whether the mission is in a mode that can execute mission items or not (is suspended).
      </description>
      <entry value="0" name="MISSION_FSM_STATE_UNKNOWN">
        <description>The mission status reporting is not supported.</description>
      </entry>
      <entry value="1" name="MISSION_FSM_STATE_NO_MISSION">
        <description>No mission on the vehicle.</description>
      </entry>
      <entry value="2" name="MISSION_FSM_STATE_NOT_STARTED">
        <description>Mission has not started. This is the case after a mission has uploaded but not yet started executing.</description>
      </entry>
      <entry value="3" name="MISSION_FSM_STATE_ACTIVE">
        <description>Mission is executing mission items (when in auto mode).</description>
      </entry>
      <entry value="4" name="MISSION_FSM_STATE_PAUSED">
        <description>Mission is paused.</description>
      </entry>
      <entry value="5" name="MISSION_FSM_STATE_COMPLETE">
        <description>Mission has executed all mission items.</description>
      </entry>
    </enum>
```

2022-08-17 05:06 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="uint8_t" name="status" enum="MISSION_STATUS">Mission status</field>
Update MISSION_STATUS to MISSION_FSM_STATE in message

```suggestion
      <field type="uint8_t" name="status" enum="MISSION_FSM_STATE">Mission finite state machine state.</field>
```

2022-08-17 05:07 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
>      </message>
Add value to indicate whether mission is in a mode where it can be executed. The actual state can always be inferred from this and the one above.

```suggestion
      <field type="uint8_t" name="mission mode" minValue="0" maxValue="2" increment="1">Vehicle is in a mode that can execute mission items (not suspended). 0: Unknown, 1: Mission mode, 2: Not in mission mode (suspended).</field>
    </message>
```

2022-08-17 05:09 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="uint16_t" name="total">Total number of mission items. 0 if no mission is present on the vehicle.</field>
```suggestion
      <field type="uint16_t" name="total" invalid="UINT16_MAX">Total number of mission items. 0: Not supported, UINT16_MAX if no mission is present on the vehicle.</field>
```

2022-08-17 05:12 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="uint8_t" name="mission mode" minValue="0" maxValue="2" increment="1">Vehicle is in a mode that can execute mission items (not suspended). 0: Unknown, 1: Mission mode, 2: Not in mis
```suggestion
      <field type="uint8_t" name="mission mode" minValue="0" maxValue="2" increment="1" invalid="0">Vehicle is in a mode that can execute mission items (not suspended). 0: Unknown, 1: Mission mode, 2: Not in mission mode (suspended).</field>
```

2022-08-17 05:13 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="uint8_t" name="status" enum="MISSION_FSM_STATE">Mission finite state machine state. MISSION_FSM_STATE_UNKNOWN if state reporting not supported.</field>
```suggestion
      <field type="uint8_t" name="status" enum="MISSION_FSM_STATE" invalid="0">Mission finite state machine state. MISSION_FSM_STATE_UNKNOWN if state reporting not supported.</field>
```

2022-08-17 05:21 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="uint8_t" name="mission mode" minValue="0" maxValue="2" increment="1" invalid="0">Vehicle is in a mode that can execute mission items (not suspended). 0: Unknown, 1: Mission mode, 2
@julianoes Do you think this needs to be an enum?

2022-08-17 05:30 UTC, hamishwillee commented
@julianoes @tridge I updated so all fields are 0 for the default "not supported" case.

In addition, have modified the reporting of state in line with the [notes above](https://github.com/mavlink/mavlink/pull/1869#issuecomment-1212621078). It now reports state using two fields. The first is the state of the mission state machine. The second is whether or not the mission is suspended (worded as whether it is in mission mode or not). That allows a recipient to absolutely know the what the mission state is.

Is it worth considering also reporting on whether jump counters are reset? If so, would making the last byte into an set of flags that includes suspended and jump counters be a better implementation?

2022-08-17 06:52 UTC, tridge commented
@hamishwillee thanks for the changes, looks much better

2022-08-17 10:25 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="uint8_t" name="mission_mode" minValue="0" maxValue="2" increment="1" invalid="0">Vehicle is in a mode that can execute mission items or suspended. 0: Unknown, 1: In mission mode, 2
An alternative. Do we like this more? I think not as much if we don't have an enum, and more if we do.

```suggestion
      <field type="uint8_t" name="suspended" minValue="0" maxValue="2" increment="1" invalid="0">Mission is suspended (is in a mode that cannot execute mission items). 0: Unknown, 1: Suspended, 2: In a mission mode (not suspended).</field>
```

2022-08-18 02:14 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="uint8_t" name="mission_mode" minValue="0" maxValue="2" increment="1" invalid="0">Vehicle is in a mode that can execute mission items or suspended. 0: Unknown, 1: In mission mode, 2
I guess not!

2022-08-18 02:18 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="uint8_t" name="mission_mode" minValue="0" maxValue="2" increment="1" invalid="0">Vehicle is in a mode that can execute mission items or suspended. 0: Unknown, 1: In mission mode, 2
minValue="0" maxValue="2" increment="1" are only for params.

```suggestion
      <field type="uint8_t" name="mission_mode" invalid="0">Vehicle is in a mode that can execute mission items or suspended. 0: Unknown, 1: In mission mode, 2: Suspended (not in mission mode).</field>
```

2022-08-18 02:27 UTC, hamishwillee commented
As discussed in dev call, this has been reviewed by ArduPilot and PX4 and can be merged.

Note that this:

- adds extension fields to the previous mission in a way such that there is no change for systems that have not updated to emit the new information.
- The previous definition said "emit on changed waypoint" while the new one says "stream". This reflects what both PX4 and ardupilot actually do. It is not inconceivable some other system might have implemented this exactly per the old spec.

Thanks for this @julianoes , and @tridge for helping me understand how ArduPlane works with missions.

2022-08-18 02:27 UTC, merged

2022-08-18 02:27 UTC, hamishwillee commented
FYI @TSC21