HIL_SENSOR updated to include windsensor measurement
mavlink/mavlink pull request #1889
Opened 2022-09-12 09:38 UTC by henrykotze

Updated HIL_SENSOR message to include new [PR](https://github.com/PX4/PX4-SITL_gazebo/pull/909) sensor added in sitl_gazebo.

2022-09-12 10:41 UTC, Jaeyoung-Lim requested changes

2022-09-12 10:41 UTC, Jaeyoung-Lim commented on message_definitions/v1.0/common.xml
> +      <field type="float" name="wind_direction" units="rad">Wind Direction</field>
I don't think we should put this as part of the `HIL_SENSOR` message, but define a new `HIL_*` message since it is not really part of a general sensor setup. Also adding this as an additional field in the mavlink message will break all other setups.

2022-09-12 14:06 UTC, henrykotze commented on message_definitions/v1.0/common.xml
> +      <field type="float" name="wind_direction" units="rad">Wind Direction</field>
Cool, I will add another HIL_* message and update it accordingly in sitl_gazebo

2022-09-14 04:01 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="float" name="wind_direction" units="rad">Wind Direction</field>
> Adding this as an additional field in the mavlink message will break all other setups that are suing this message definition.

@Jaeyoung-Lim Unless simulators use MAVLink 1 (?) you could add these fields as MAVLInk 2 extensions. 

I have no particular opinion whether it should more generally be the same or a different message. But if we're defining another message we should make sure that all the fields that might be useful are considered for addition.

@henrykotze When these are added 
1. You will need to specify the reference yaw for wind direction - is it NED or fixed the vehicle attitude or something else?
2. If it is possible that this information will not be sent by a  simulator then specify a value to indicate "we're sending invalid data". For a float this is usually NaN.

2022-09-14 04:02 UTC, hamishwillee commented
Closing, as it sounds like the proposal is to have a new message.

2022-09-14 04:02 UTC, closed without merging