RADIO_RC_CHANNELS message
mavlink/mavlink pull request #1919
Opened 2022-11-16 22:18 UTC by olliw42

Suggestion for a new RADIO_RC_CHANNELS message.

The backgorund is given in the issue xxx.

If generally approved, the details of it may be discused here in this PR.

2023-11-28 09:54 UTC, olliw42 commented
list of points which occured in discussions
- **message id**: The message is currently located in storm32.xml with an id in the storm32.xml's range. It doesn't smell correct to keep that id when moved to development. So I changed it. One could use any free id in the mavlink2 range as onenromally would do. In this PR I however suggest to use a gap in the mavlink1 area, which could host a number of releated messages. Personally I totally do not care, so fill happily follow any suggestion. It just needs to be decided.
- **target fields**: The message has no target fields, and it is proposed that the desired targeting is achieved by special code in the routers, similar to how the existing RADIO_STATUS is handled. This can be much debated, with pros and cons, but a decission needs to be made.
- **source system id**: The receivers sending out this message are supposed to have a source system id different from the vehicle/system they are connected to. Typically 51. This is similar to SiK radios and alike.
- The receivers are normally not supposed to send HEARTBEAT messages (unless they want to support microservices, like e.g. parameters)
 
The message originally was sugested to carry 24 channels max. I have extended to 32 channels, since due to zero-padding it doesn't cost anything but may make it super future proof.

2023-12-06 05:55 UTC, olliw42 commented
@hamishwillee maybe I can direct your attention towards this PR for a moment. Last week there had been some encouraging activity on the ArduPilot side with respect of implementing the proposed RADIO_RC_CHANNELS message, and the ArduPilot devs seem to have generally agreed to the concept: https://github.com/ArduPilot/ardupilot/pull/24577#pullrequestreview-1751596027, https://github.com/ArduPilot/ardupilot/pull/24577#pullrequestreview-1751592965. While activity has lowered a bit, I think it could be the appropriate time to discuss and settle the topic of which _**message id**_ to choose.

Since besides RADIO_RC_CHANNELS there would be few more messages in the "RADIO series", it could make sense to look for slots of 5 messages or so (I currently do see 4 messages).  

The PR currently suggests a message id in the MAVLink v1 range, namely 95, as there happens to be a free slot from 93 - 99.

The canonical approach would be to occupy the "next" slot in the MAVLink v2 area, which seems to be 420 currently.

All I would want you to decide is if 95 is ok to choose, with the understanding that it essentially would reserve the slot 95-99, or if I should change the PR to use 420?

Personally I have no real opinion here, It just needs to be decided. :)

THX. Olli

2023-12-06 06:29 UTC, hamishwillee commented
IMO the range should change to something above 256. It doesn't have to be 420 - but if that looks like a good free block then sure.

2023-12-06 06:40 UTC, olliw42 commented
ok, I'll change. Many thx!!

2023-12-13 08:07 UTC, peterbarker requested changes

2023-12-13 08:07 UTC, peterbarker commented on message_definitions/v1.0/development.xml
> +    </message>
No RSSI or LQ?  People really like having this!

2023-12-13 08:35 UTC, olliw42 commented on message_definitions/v1.0/development.xml
> +    </message>
NO!!

I'm a bit inclined to direct you to the fuller discussion https://github.com/mavlink/mavlink/issues/1921, but you sure deserve a briefer response. 

It's IMHO a strength of the suggested concept to separate the rc data from the link stats data, for a number of reasons. The link stats data is carried in the proposed RADIO_LINK_STATS message, the upstream PR is https://github.com/mavlink/mavlink/pull/1920. 

The intention is clearly that once the RADIO_RC_CHANNELS thing should have been accepted, to also raise the PR to bring in the RADIO_LINK_STATS. The code is available since long. The proposed RADIO_LINK_STATS message has seen btw already substantial discussion, since it was the template for a similar DroneCAN message.
So, in short, the link stats PR will follow.

2023-12-26 01:36 UTC, peterbarker commented on message_definitions/v1.0/development.xml
> +    </message>
OK, had a quick read of the relevant section in the linked issue - that's a fair argument, thanks!

2024-01-29 09:14 UTC, olliw42 commented
@hamishwillee 
FYI, the topic of this PR has made progress: 
The RADIO_RC_CHANNELS message and potential implementation in ArduPilot has been dicussed intensively over at ArduPilot, and there is now a PR in the ardupilot mavlink repository which from "our" point of view might be short of being accepted.

So, it would be great to also get your input. 

I kindly want to ask you to look over it and comment in the ArduPilot repo: https://github.com/ArduPilot/mavlink/pull/343
It would safe me from substantial double-burden - once the message has been merged to the ArduPilot mavlink repo I will update this PR here to be in sync, so that the two repos don't stray away. Hope you find this ok.

The main changes to the message proposed here had been
- adding target fields
- adding a time stamp for the when the rc data was valid the last time
- more comments in the description

THX

2024-01-31 03:31 UTC, hamishwillee commented on message_definitions/v1.0/development.xml
> +      <extensions/>
Given the id is changing anyway, the message is breaking. So we don't need extensions.

2024-01-31 03:31 UTC, hamishwillee commented on message_definitions/v1.0/development.xml
> +      <extensions/>
```suggestion
```

2024-01-31 03:32 UTC, hamishwillee commented on message_definitions/v1.0/development.xml
> +      <field type="uint8_t" name="count">Total number of RC channels being received. This can be larger than 24, indicating that more channels are available but not given in this message.</field>
?
```suggestion
      <field type="uint8_t" name="count">Total number of RC channels being received. This can be larger than 32, indicating that more channels are available but not given in this message.</field>
```

2024-01-31 03:45 UTC, hamishwillee commented on message_definitions/v1.0/development.xml
> +      <field type="uint8_t" name="count">Total number of RC channels being received. This can be larger than 24, indicating that more channels are available but not given in this message.</field>
Argg. I'll look on the one on ArduPilot.

2024-01-31 05:15 UTC, hamishwillee commented
@olliw42 Re https://github.com/mavlink/mavlink/pull/1919#issuecomment-1914268242 I have put in some comments, which hopefully make sense. The little picture is
- Extensibility - how many channels
- How does the timestamp and RC-lost behaviour work

The big picture is "can this be a single path for analog manual control input" with Joystick. Essentially addressing James comments in https://github.com/mavlink/mavlink/issues/1921#issuecomment-1331303555

Other than that, we probably need review from someone like @ThomasDebrunner and @julianoes - but let's see if my questions make any sense to you first :-)

2024-01-31 06:38 UTC, olliw42 commented
MANY thx for looking at it
I'll comment in the ArduPilot PR https://github.com/ArduPilot/mavlink/pull/343#issuecomment-1918417134, if you allow.

2024-01-31 07:19 UTC, hamishwillee commented
Of course. Looks like broader interest :-)

2024-02-29 06:15 UTC, olliw42 commented
@hamishwillee brings in the changes to RADIO_RC_CHANNELS discussed in https://github.com/ArduPilot/mavlink/pull/343

also removes all other related enums/messages from the storm32.xml, as it seems it's all going to come :)

2024-02-29 06:18 UTC, olliw42 commented
ups, error ... it seems you had added minValue/maxValue fields to the message which are in ardupilot's repo but not yet in the schema here ... what to do? I guess you need to update the schema ...

2024-03-01 10:46 UTC, olliw42 commented
@hamishwillee removed the offending minValue,maxValue attributes, so that this message can be merged as soon as possible, I think the minValue,maxValue can be reinserted once the schema is done.

2024-03-06 07:07 UTC, hamishwillee commented
The schema should have come back in today. If you can add back I'll merge tomorrow.

2024-03-06 07:30 UTC, olliw42 commented
done :)

2024-03-06 07:45 UTC, merged

2024-03-06 10:27 UTC, olliw42 commented
THX!