remove invalid enum reference from storm32.xml
mavlink/mavlink pull request #1947
Opened 2023-02-03 17:27 UTC by aler9

#1941 contains an invalid enum reference that breaks generation of external libraries.

I searched for the enum definition but i couldn't find it, therefore it should be removed unless @olliw42 provides it.

2023-02-03 19:43 UTC, olliw42 commented
omg, indeed ... MANY thx!

could you please also change the date to 3. Feb. 2023 (it seems one can't do a suggestion for non modified lines)

2023-02-04 03:01 UTC, olliw42 requested changes

2023-02-04 10:27 UTC, aler9 commented
@olliw42  all done.

2023-02-04 13:00 UTC, olliw42 commented
perfect, many thx sir :)

it's interesting that some generators do test for such things...

2023-02-04 13:06 UTC, aler9 commented
@olliw42 in some strongly typed languages, an enum corresponds to a dedicated type. If the enum doesn't exist, the field has an invalid type.

While in C, that is still a strongly typed language, an enum-based field may be converted into

```c
#define ENUM_MYENUM_VAL1 1
#define ENUM_MYENUM_VAL2 2

typedef struct {
  uint16_t my_field;
} mymsg;
```

In Typescript, it is converted into

```typescript
enum myenum {
  myval1 = 1,
  myval2 = 2,
}

type mymsg = {
  my_field: myenum
};
```

In Golang, it is converted into


```go
type myenum int

const (
  myval1 myenum = 1
  myval2 myenum = 2
)

type mymsg struct {
  my_field myenum
}
```

Therefore myenum must exist.

2023-02-04 13:17 UTC, olliw42 commented
ah, it's not a generator thing but a language thing
thx for the insight :)

2023-02-07 23:43 UTC, hamishwillee approved these changes
@olliw42 I'm taking your comment as approval and merging :-)

2023-02-07 23:43 UTC, merged