common.xml: EGM96 is geoid not ellipsoid
mavlink/mavlink pull request #2168
Opened 2024-11-07 02:23 UTC by hamishwillee

This addresses (as small part of) #2167 - EGM96 is referred to as an ellipsoid but is actually a  geoid

2024-11-07 02:30 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="int32_t" name="lat" units="degE7">Latitude (WGS84, EGM96 geoid)</field>
Should these (all) be like:

```suggestion
      <field type="int32_t" name="lat" units="degE7">Latitude (WGS84 ellipsoid, EGM96 geoid)</field>
```

In fact though, is "EGM96 geoid" even relevant here, since the latitude is from GPS, which uses WGS84?

2024-11-07 02:34 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="int32_t" name="alt_ellipsoid" units="mm">Altitude (above WGS84, EGM96 geoid). Positive for up.</field>
So presumably these are different references, so saying both is by definition wrong. Should this actually be:

```suggestion
      <field type="int32_t" name="alt_ellipsoid" units="mm">Altitude (EGM96 geoid). Positive for up.</field>
```

2024-11-07 02:37 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
>        <field type="int32_t" name="alt" units="mm">Altitude (MSL). Positive for up. Note that virtually all GPS modules provide the MSL altitude in addition to the WGS84 altitude.</field>
```suggestion
      <field type="int32_t" name="alt" units="mm">Altitude (EGM96 ellipsoid/MSL). Positive for up. Note that virtually all GPS modules provide the EGM96 altitude in addition to the WGS84 altitude.</field>
```

2024-11-07 02:38 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="int32_t" name="alt_ellipsoid" units="mm">Altitude (above WGS84, EGM96 geoid). Positive for up.</field>
```suggestion
      <field type="int32_t" name="alt_ellipsoid" units="mm">Altitude (above WGS84 ellipsoid). Positive for up.</field>
```

2024-11-07 03:07 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="float" name="altitude_amsl" units="m">This altitude measure is strictly above Mean Sea Level (MSL) and might be non-monotonic (it might reset on events like GPS lock or when a new
What should we do if this is "strictly AMSL"? Is this a synonym?

2024-11-07 03:14 UTC, Ryanf55 commented on message_definitions/v1.0/common.xml
> +        - "RELATIVE_ALT": Altitude is relative to the vehicle home position rather than EGM96 geoid.
```suggestion
        - "RELATIVE_ALT": Altitude is relative to the vehicle home position
```
This would be clear enough. Can we bold `relative`?

2024-11-07 03:15 UTC, Ryanf55 commented on message_definitions/v1.0/common.xml
> +        <description>Global (WGS84) coordinate frame + altitude relative to EGM96 geoid.</description>
```suggestion
        <description>Global (WGS84) coordinate frame + altitude above the EGM96 geoid.</description>
```
Above now means that positive altitude is towards the sky.

2024-11-07 03:15 UTC, Ryanf55 commented on message_definitions/v1.0/common.xml
> +      <field type="int32_t" name="lat" units="degE7">Latitude (WGS84, EGM96 geoid)</field>
I would say `Latitude (WGS84 ellipsoid)`. From what I understand, EGM96 is not related, but I can confirm in geographiclib by converting the same lat-lon pair to ECEF and comparing the results.

2024-11-07 03:17 UTC, Ryanf55 commented on message_definitions/v1.0/common.xml
> +      <field type="int32_t" name="alt" units="mm">Altitude (EGM96 geoid). Positive for up. Note that virtually all GPS modules provide the EGM96 geoid altitude (as MSL) in addition to the WGS84 altit
```suggestion
      <field type="int32_t" name="alt" units="mm">Altitude (EGM96 geoid). Positive for up. Note that virtually all GPS modules provide the EGM96 geoid altitude (as MSL) in addition to the WGS84 ellipsoid altitude.</field>
```

2024-11-07 03:18 UTC, Ryanf55 commented on message_definitions/v1.0/common.xml
> +      <field type="int32_t" name="alt" units="mm">Altitude (EGM96 geoid). Note that virtually all GPS modules provide both WGS84 and EGM96 geoid ("MSL").</field>
I'm tempted that we should remove `Note that virtually all GPS modules provide both WGS84 and EGM96 geoid ("MSL").`

That better belongs in some primer documentation on coordinate system that explains how GPS's support both, and what mavlink uses, and some sample code on how to convert the two.

2024-11-07 03:19 UTC, Ryanf55 commented on message_definitions/v1.0/common.xml
> +      <field type="int32_t" name="altitude" units="mm">Altitude (EGM96 geoid). Positive for up.</field>
FYI, the most clear/pedantic I can think of is:
`(MSL using the EGM96 geoid)`

2024-11-07 03:21 UTC, Ryanf55 commented on message_definitions/v1.0/common.xml
> +      <field type="float" name="altitude_amsl" units="m">This altitude measure is strictly above Mean Sea Level (MSL) and might be non-monotonic (it might reset on events like GPS lock or when a new
```suggestion
      <field type="float" name="altitude_amsl" units="m">This altitude measure is strictly above Mean Sea Level (MSL) and might be non-monotonic (it might reset on events like GPS lock or when a new QNH value is set). It should be the altitude to which global altitude waypoints are compared to. Note that it is *not* the GPS altitude, however, most GPS modules already output EGM96 geoid (MSL) by default and not the altitude above the WGS-84 ellipsoid.</field>
```

2024-11-07 03:22 UTC, Ryanf55 commented on message_definitions/v1.0/common.xml
> +      <field type="float" name="altitude_amsl" units="m">This altitude measure is strictly above Mean Sea Level (MSL) and might be non-monotonic (it might reset on events like GPS lock or when a new
I don't actually know what this is trying to say about it not being the GPS altitude.

2024-11-07 03:29 UTC, Ryanf55 commented
Regarding the question `Currently the assumption is that GPS modules output MSL and this is calculated by some consistent formula. If MSL is always a proxy for EGM96 we're fine. IF not, then we need to think a bit more about what we are expecting implementers to actually do here, and what implications that would have on drones/SDKs that have been getting the data in some other format.`

The reality is that ArduPilot, by default on UBX, which is the most common solution, it outputs Ublox's approximated MSL height which is a poor approximation of the EGM-96 geoid, and no one has ability to convert from UBX MSL to any other standard.

This PR allows you to change that, abuse the mavlink spec, and populate the mavlink packets with ellipsoid height.
https://github.com/ArduPilot/ardupilot/pull/20979/files#diff-94452a535dc39cfc290c8900b32ea3775725649a9adf73666e55bd9467d8603bR1288

Quite the simple solution from ArduPilot's side, but functionally I believe it abuses the mavlink spec and would not work in MAVROS which assumes it's always EGM96.

2024-11-07 03:52 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +        - "RELATIVE_ALT": Altitude is relative to the vehicle home position rather than EGM96 geoid.
> Can we bold relative?

Not safely. These docs get spit out into various generators. I would like to be able to support markdown (minus HTML) here, but that would require a lot of testing.

2024-11-07 03:55 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +        <param index="3" label="Max Altitude" units="m">Altitude (EGM96 geoid) max - if vehicle moves above this alt, the command will be aborted and the mission will continue. 0 means no upper altit
```suggestion
        <param index="2" label="Min Altitude" units="m">Altitude min (EGM96 geoid) - if vehicle moves below this alt, the command will be aborted and the mission will continue. 0 means no lower altitude limit.</param>
        <param index="3" label="Max Altitude" units="m">Altitude max (EGM96 geoid) - if vehicle moves above this alt, the command will be aborted and the mission will continue. 0 means no upper altitude limit.</param>
```

2024-11-07 03:56 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="int32_t" name="lon" units="degE7">Longitude (WGS84, EGM96 geoid)</field>
```suggestion
      <field type="int32_t" name="lon" units="degE7">Longitude (WGS84 ellipsoid)</field>
```

2024-11-07 03:57 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="int32_t" name="lat" units="degE7">Latitude (WGS84, EGM96 geoid)</field>
SHouldn't matter - we know we mean WGS84 - since we mean that everywhere else for lat/lon. And if they are not the same, then the geoid value is wrong anyway.

2024-11-07 03:59 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="int32_t" name="alt" units="mm">Altitude (EGM96 geoid). Note that virtually all GPS modules provide both WGS84 and EGM96 geoid ("MSL").</field>
I agree. Probably an important point when this was written originally, but not now.

```suggestion
      <field type="int32_t" name="alt" units="mm">Altitude (EGM96 geoid).</field>
```

2024-11-07 04:03 UTC, hamishwillee commented on message_definitions/v1.0/common.xml
> +      <field type="int32_t" name="altitude" units="mm">Altitude (EGM96 geoid). Positive for up.</field>
I like mentioning MSL because it means something to people, but if we are standardizing on the geoid then this meaning is largely irrelevant, except for cases where we have named fields with `msl` or `amsl` and need to explain them.

Let's see how this all pans out and then make any change like that globally.

2024-11-13 07:01 UTC, hamishwillee commented
Thanks. I've added this to next call agenda, so we'll discuss it then, if not before https://github.com/mavlink/mavlink/wiki/20241120-Dev-Meeting

2024-11-20 21:37 UTC, hamishwillee commented
We discussed in the MAV call:.
- Historically most global altitude references in MAVLink have been "relative to MSL", and the value was interpreted to be be "whatever the GPS/GNSS output MSL". By far the most commonly used GPS  were based on UBLOX and this output MSL according to its own (possibly proprietary) algorithm.

Now we're getting lots more GNSS systems, and they don't share a common MSL reference. My understanding is that ArduPilot is taking the decision to reinterpret all the MSL references as "relative to the EGM96 geoid". The argument being that the sender will abstract the differences in GNSS modules and send a consistent altitude for a given latitude/longitude.

The MAV call take on this is that it is a good idea:
- Its a lot of churn, but the altitude reference is effectively broken as defined. We either need to define it as "UBLOX MSL" or change to some other predictable reference. We'd rather do something that isn't proporietary
- We're concerned about 2nd order effects of this and mitigating them. For example, is it likely any receiving code would be broken by this, and would it be useful to provide a protocol bit to indicate that references are now standardized?
- We'd like PX4 to standardize on this too before we make a decision.

@julianoes Says that PX4 currently collects but does not use the  EGM96 geoid, except to publish it in those messages which include the "altitude_ellipsoid" field.

@dagar Is it possible/reasonable to start using the EGM96 geoid where ublox MSL is currently used, and publishing the EGM96 geoid relative values in messages that currently publish "MSL altitude"?



@dagar @tridge

2024-11-20 22:21 UTC, julianoes commented
FYI @bresch.

Related: https://github.com/PX4/PX4-Autopilot/pull/23854

2024-11-20 23:12 UTC, hamishwillee commented
Thanks @Ryanf55 

A few ideas
- Add an enum field that specifies the reference to all these messages, with default 0 value, with strong preference for EGM-96. So rather than saying "Altitude MSL". It would say "Altitude, with reference defined in field X. That way you can at least know your reference.
- Add protocol bit that says EGM-96 supported as altitude reference
  - GPS that can't do this conversion does not set the bit. Autopilot can choose to convert if it wants to compile in the conversion library

Historically we would prefer the enum option. Autopilots tend to just supply and support one or two options. A GCS could then do conversion for the other options it needed.

I don't know the implications of changing to WGS-84 ellipsoid height. I think we really need to know what ArduPilot/@tridge would prefer and we can then seek consensus.

2024-11-20 23:50 UTC, Ryanf55 commented
> Thanks @Ryanf55
> 
> A few ideas
> 
> * Add an enum field that specifies the reference to all these messages, with default 0 value, with strong preference for EGM-96. So rather than saying "Altitude MSL". It would say "Altitude, with reference defined in field X. That way you can at least know your reference.
> * Add protocol bit that says EGM-96 supported as altitude reference
>   
>   * GPS that can't do this conversion does not set the bit. Autopilot can choose to convert if it wants to compile in the conversion library
> 
> Historically we would prefer the enum option. Autopilots tend to just supply and support one or two options. A GCS could then do conversion for the other options it needed.
> 
> I don't know the implications of changing to WGS-84 ellipsoid height. I think we really need to know what ArduPilot/@tridge would prefer and we can then seek consensus.

I pinged him on discord for insights.

2024-11-21 04:00 UTC, Jaeyoung-Lim commented
@hamishwillee Note that there are newer EGM models, and therefore, we would need to expand the fields as we go.

Have you considered just specifying the epsg code for the vertical datum?

2024-11-26 23:15 UTC, hamishwillee commented
> @hamishwillee Note that there are newer EGM models, and therefore, we would need to expand the fields as we go. Moreover, EGM is not the only geoid model, so we would end up needing a lot of enums to fully cover all GPS setups.
> Have you considered just specifying the epsg code for the vertical datum?

@Jaeyoung-Lim FYI I absolutely abhor any discussion to do with positioning, datums, frames of reference etc. They are fundamental, but I know little about them. Further, everyone has an opinion, and they only ever share it when they aren't happy, usually after the two or three who showed up to discuss have resolved the issue and posted the change.

That's just for context.

- IMO MAVLink should have just one altitude reference and everyone would be required to output it or convert to it. I'd have been happy with MSL if that hadn't become synonymous with "whatever Ublox outputs". 
- I really don't want to have an enum an have every datum/reference under the sun because I know from experience it is likely that this will be confusing for users 
  - in practise what happens is that there will be only one used by 95%, a couple of niche variants which are poorly supported by flight stacks and GCS, and the rest which have no implementation. Much better to just have one that the ecosystem can rely on.
  - Even if we allow this to be output, I would expect that any setters of altitude would have to be relative to some fixed reference - we know that we don't want to mandate a conversion library on the flight stacks because they take a lot of flash.
- EGM seems to be broadly supported. But as I say, I couldn't care less what we select as long as it is something either output by lots of GNSS modules or can easily be converted to by what they support.

> Have you considered just specifying the epsg code for the vertical datum?

No, because I don't know what that means. Is it something that meets the above requirements, how does it help? @Ryanf55 Thoughts?

2024-11-26 23:48 UTC, hamishwillee commented
PS there is a "spot solution" being proposed in https://github.com/mavlink/mavlink/pull/2146#discussion_r1851251125.
Grrr.

2024-11-27 02:08 UTC, Ryanf55 commented
> > @hamishwillee Note that there are newer EGM models, and therefore, we would need to expand the fields as we go. Moreover, EGM is not the only geoid model, so we would end up needing a lot of enums to fully cover all GPS setups.
> > Have you considered just specifying the epsg code for the vertical datum?
> 
> @Jaeyoung-Lim FYI I absolutely abhor any discussion to do with positioning, datums, frames of reference etc. They are fundamental, but I know little about them. Further, everyone has an opinion, and they only ever share it when they aren't happy, usually after the two or three who showed up to discuss have resolved the issue and posted the change.
> 
> That's just for context.
> 
> > Have you considered just specifying the epsg code for the vertical datum?
> 
> No, because I don't know what that means. Is it something that meets the above requirements, how does it help? @Ryanf55 Thoughts?
> 
IF we were to continue to use MSL, I agree EPSG code is the most universally accepted way to signify which datum.


> 
> * MAVLink should have just one altitude reference and everyone would be required to output it or convert to it. I'd have been happy with MSL if that hadn't become synonymous with "whatever Ublox outputs" which is a proprietary algorithm.
> * I really don't want to have an enum an have every datum/reference under the sun because I know from experience it is likely that this will be confusing for users
>   
>   * in practice what happens is that there will be only one used by 95%, a couple of niche variants which are poorly supported by flight stacks and GCS, and the rest which have no implementation. Much better to just have one that the ecosystem can rely on being used to get and set alts.
>   * Even if we allow this to be output, I would expect that any setters of altitude would have to be relative to some fixed reference - we know that we don't want to mandate a conversion library on the flight stacks because they take a lot of flash.
> * EGM seems to be broadly supported. But as I say, I couldn't care less what we select as long as it is something either output by lots of GNSS modules or can easily be converted to by what they support.


I think WGS-84 ellipsoid height is more universally supported than EGM96. We currently have no way to convert from UBX MSL to ANY other datum if MAVLink only publishes UBX MSL data. The only other thing UBX receivers support other than UBX MSL is WGS-84 ellipsoid.

I propose taking a look through the manuals of the common GPS's, and checking if they can all support WGS-84 ellipsoid height. Once you have WGS-84 ellipsoid, then it's pretty easy to convert to EGM96 or whatever geoid height you want. 

If all the GPS's we care about support WGS-84 ellipsoid, then that's an easy option. 

> The other consideration is migration. Changing any message is hard. Changing something this fundamental is near impossible. I think I can just about get agreement that we settle on the MSL fields being modified to be something like EGM, since that is a close approximation to MSL (Apparently).

I would like more input from the ArduPilot devs on whether they see a migration path with the current messages, or there needs to be a new set of messages.

2024-11-27 02:15 UTC, hamishwillee commented
> I would like more input from the ArduPilot devs on whether they see a migration path with the current messages, or there needs to be a new set of messages.

Me too. @peterbarker Plans to raise this in the ArduPilot dev call this evening I believe. 

I'm OK with WGS-84 too, but if we do that we still need to advertise this is the data format for setters/getters.

2024-11-27 05:37 UTC, Ryanf55 commented
Absolutely. Thoughts on a bit in [MAV_PROTOCOL_CAPABILITY](https://mavlink.io/en/messages/common.html#MAV_PROTOCOL_CAPABILITY) that autopilot supports WGS-84 ellipsoid height for all GLOBAL frames? We then can update the mavlink spec to be either GPS defined MSL altitude OR WGS-84 ellipsoid height depending on that bit. 

After talking with @peterbarker  and Thomas, we don't see any huge problems with switching ArduPilot internally to WGS-84 because all the GPS drivers we looked at support it. Some are currently publishing data in WGS-84 already!

The one complexity was what to do with our terrain data that is in EGM-96. 

We'll still need to figure out a migration strategy for GCS's if this bit is turned on.

2024-11-27 05:41 UTC, Ryanf55 commented
We thought it made sense to put together a list of protocols and which datums they support. I'll update this table with more info over time. 

| Vendor | Protocol | Position Coordinates Supported| 
| Trimble | GSOF | [WGS-84](https://receiverhelp.trimble.com/alloy-gnss/en-us/gsof-messages-llh.html?tocpath=Output%20Messages%7CGSOF%20messages%7C_____16) , [ECEF](https://receiverhelp.trimble.com/alloy-gnss/en-us/gsof-messages-ecef.html?tocpath=Output%20Messages%7CGSOF%20messages%7C_____27) |

2024-11-27 07:25 UTC, tridge requested changes

2024-11-27 07:25 UTC, tridge commented on message_definitions/v1.0/common.xml
> +      - "GLOBAL": Global coordinate frame with WGS84 latitude/longitude and altitude positive over EGM96 geoid (approximately Mean Sea Level - MSL) by default.
unless we have some computationally feasible way of generating accurate EGM96 then this is a misleading change, as flight controllers running STM32 MCUs won't be able to calculate the value

2024-11-27 07:36 UTC, tridge commented on message_definitions/v1.0/common.xml
> +      - "GLOBAL": Global coordinate frame with WGS84 latitude/longitude and altitude positive over EGM96 geoid (approximately Mean Sea Level - MSL) by default.
it would also mean that all current flight controllers would be instantly non-compliant, which doesn't seem good

2024-11-27 16:38 UTC, Ryanf55 commented
Here's some notes from the ArduPiot EU dev call on 2024-11-27:
https://discuss.ardupilot.org/t/ardupilot-eu-dev-call-2024-11-27/126834

* The team is largely opposed to codifying EGM-96 in MAVLink because we can't implment this with UBX easily
* The original design intent for the terrain server and GPS's was for planes flying high enough they could neglect the differences in MSL and WGS-84 ellipsoid height, including the terrain protocol
* We are pretty sure the SRTM terrain on ArduPilot is EGM-96
* The short term solution for users is to enable [GPS_DRV_OPTIONS](https://ardupilot.org/plane/docs/parameters.html#gps-drv-options-driver-options) bit 4, which has the vehicle fly in ellipsoid height. This knowing divergent with the terrain height, so it is not suitable for low altitude flying UNLESS you have a rangefinder
* We see a long-term option to use WGS-84 ellipsoid height with the following work required. This is a LARGE effort
   * We evaluated all our GPS's and suspect they can all support WGS-84 height, so we would need to add GPS_DRV_OPTIONS bit 4 support to the rest of the drivers
   * We would need to augment our terrain server with a new dataset that can serve data in WGS-84 ellipsoid height
   * We need to either locate a terrain data source for WGS-84 ellipsoid height or process the data ourselves
   * AP would need to increase it's terrain server memory, perhaps $1000/yr increase in cost to suppor this new data
   * The mavlink terrain protocol would need an addition to have a datum field
   * The ground stations would need an update to be able to request ellipsoid terrain data and to serve ellipsoid data to the FC
   * The mavlink spec needs a way for commands to be in ellipsoid mode. We don't have any strong preference yet, however we could add a new [MAV_FRAME](https://mavlink.io/en/messages/common.html#MAV_FRAME) such as MAV_FRAME_GLOBAL_WGS84_ELLIPSOID, or a protocol bit
   * DroneCAN also would need protocol changes
* In the near term, I think it makes sense to close this PR because EGM-96 is not feasible.
* We could improve the mavlink documentation to fix mixups of EGM-96, WGS-ellipsoid, and just call things MSL
* We could improve the  mavlink documentation to add an addendum on MSL that users who want to fly MAV_FRAME_GLOBAL that use terrain data need to be aware that most flight stacks have divergent MSL frames and there is no solution yet

2024-11-28 02:06 UTC, hamishwillee commented
Thanks @Ryanf55 @tridge 

I was under the misapprehension that EGM-96 was a reasonable "proxy" for MSL (i.e. no worse than just saying "MSL") that could be output by the vast majority of GNSS modules. Given that neither of these are true it doesn't make sense to continue this PR.

IMO we should clean up what we know to be wrong now without attempting to make this future-proof.

1. Anywhere we say MSL we should make it clear that its is _GNSS-specific_. So where it now says:
   ```xml
   <description>Global (WGS84) coordinate frame + altitude relative to mean sea level (MSL).</description>
   ```
   Perhaps
   ```xml
   <description>Global (WGS84) coordinate frame + altitude relative to GNSS-specific mean sea level (MSL).</description>
   ```
2. [GPS_RAW_INT.alt_ellipsoid](https://mavlink.io/en/messages/common.html#GPS_RAW_INT) and [GPS2_RAW](https://mavlink.io/en/messages/common.html#GPS2_RAW) say
   > Altitude (above WGS84, EGM96 ellipsoid). Positive for up.
   
   It can't be both, EGM96 is a geoid not an ellipsoid, and even if it can be either, there is no way to tell which it is.
   Propose we make this just WGS84 since we believe this can be output by most, and we know EGM96 cannot. OK?
   
   > Altitude (above WGS84 ellipsoid). Positive for up.
   
   Alternatively we just change ellipsoid to geoid and ignore this, eventually replacing with the new GPS raw message.

3. In same messages lat/lon state 
   
   > Latitude (WGS84, EGM96 ellipsoid)
   
   We should change to this, because EGM96 uses the same lat/lon reference as WGS84).
   
     > Latitude (WGS84 ellipsoid) 

@tridge Would you be OK with those changes?

2024-11-28 02:28 UTC, Ryanf55 commented
Agree, here's some responses in case you wanted to get this up for PR sooner than later.


> 
> IMO we should clean up what we know to be wrong now without attempting to make this future-proof.
> 
> 1. Anywhere we say MSL we should make it clear that its is _GNSS-specific_. So where it now says:
>    ```
>    <description>Global (WGS84) coordinate frame + altitude relative to mean sea level (MSL).</description>
>    ```
>    
>    Perhaps
>    ```
>    <description>Global (WGS84) coordinate frame + altitude relative to GNSS-specific mean sea level (MSL).</description>
>    ```

Agree

> 2. [GPS_RAW_INT.alt_ellipsoid](https://mavlink.io/en/messages/common.html#GPS_RAW_INT) and [GPS2_RAW](https://mavlink.io/en/messages/common.html#GPS2_RAW) say
>    > Altitude (above WGS84, EGM96 ellipsoid). Positive for up.
>    
>    
>    It can't be both, EGM96 is a geoid not an ellipsoid, and even if it can be either, there is no way to tell which it is.
>    Propose we make this just WGS84 since we believe this can be output by most, and we know EGM96 cannot. OK?
>    > Altitude (above WGS84 ellipsoid). Positive for up.

Agree, plus the field name has ellipsoid in it. GPS drivers should ensure it populates ellipsoid data. 
ArduPilot is currently populating ellipsoid height as it should. 
https://github.com/ArduPilot/ardupilot/blob/10209a2a13ec82fad946164c13035d7eb13a524e/libraries/AP_GPS/AP_GPS.cpp#L1371-L1397


> 3. In same messages lat/lon state
>    > Latitude (WGS84, EGM96 ellipsoid)
>    
>    
>    We should change to this, because EGM96 uses the same lat/lon reference as WGS84).
>    > Latitude (WGS84 ellipsoid)

Agree

2024-12-04 00:55 UTC, hamishwillee commented
OK, closing this. Replacement, which also has things for discussion, in #2190

2024-12-04 00:55 UTC, closed without merging